name: Release on play store

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build && npx cap copy && npx cap update

      - name: Bump version
        uses: ults-io/mobile-version-bump-action@v2
        with:
          android-project-path: ./android 
          app-version:         versionName "${{ github.ref_name }}"

      - name: Check bumped version
        run: |
          cat android/app/build.gradle
          
      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Bundle release
        env:
          KEYSTORE_FILE: android/release.decrypted.jks
          KEY_ALIAS: grimoar
          KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload to playstore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          packageName: com.clochard.grimoar
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: qa



