name: Build Android
run-name: Creating Unsigned Android App 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install dependencies
        run: yarn

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle


      - name: Save release bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/release/*.apk