name: Build Android
run-name: Creating Unsigned Android App 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: install dependencies
        run: yarn

      - name: Build Ionic App
        run: npx ionic build

      - name: Copy Android
        run: npx ionic capacitor copy android

      - name: Build Android Dev APK
        run: npx ionic capacitor build android

      - name: Build Android Release APK
        run: npx ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Check build files
        run:
          ls android
          ls android/app
          ls android/app/build
          ls android/app/build/outputs
          ls android/app/build/outputs/apk
          ls android/app/build/outputs/apk/release

      - name: Save release bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk