name: Build Android
run-name: Creating Unsigned Android App 🚀
on:
  push:
    branches:
      - master
  workflow_dispatch:
    

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: install dependencies
        run: yarn

      - name: Create Build Folder
        run: yarn run build

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy
      
      # TODO: Check for folder structure in README for generating splash screen 
      - name: Generate icons and splash screen to android folder 
        run:  npx capacitor-assets generate --android
        
      - name: Build apk
        run: cd android && ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-apk
          path: ./android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Set Tag
        id: current-datetime
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H_%M_%S%z')" >> "$GITHUB_OUTPUT"
