name: Build Android
run-name: Creating Unsigned Android App 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: install dependencies
        run: yarn

      - name: build vite
        run: npx ionic capacitor build android

      - name: signinReport
        working-directory: ./android/
        run: ./gradlew signinReport

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew build

      - name: Save release bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk